### ISSUE TITLE
app 

### ISSUE THREAD

**Issue by avishayhajbi** [JoaoCnh/react-native-android-voice#17]
i got this error when stop recording : 

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.writeit, PID: 3567
                                                           java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
                                                               at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
                                                               at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:620)
                                                               at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
                                                               at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
                                                               at android.app.Activity.dispatchActivityResult(Activity.java:6463)
                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3785)
                                                               at android.app.ActivityThread.access$1400(ActivityThread.java:157)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

**Comment by JoaoCnh** [comment]
Is it a persistent error? Any more details?

**Comment by avishayhajbi** [comment]
It happens every time i try to record something

**Comment by JoaoCnh** [comment]
What versions are you running?

**Comment by avishayhajbi** [comment]
LG g4 android version 6
"react": "15.3.2",
"react-native": "^0.35.0",
"react-native-android-voice": "^0.3.0",

**Comment by JoaoCnh** [comment]
I've just published v0.5.0. Please check if issues still persist for any of you and please feel free to report new ones.

Many thanks to everyone who contributed for v0.5.0 with PRs

**Comment by JoaoCnh** [comment]
@avishayhajbi Is the issue still persisting with v0.5.0?

**Comment by JoaoCnh** [comment]
@avishayhajbi is it working with v0.5.1? I'll close this issue for now. Feel free to re-open
